image: openjdk:8

variables:
  PROJECTNAME: "ManiaCentering"

before_script:
  - java -version

stages:
  - compile
  - status
  - javadoc

pending:
  allow_failure: true
  script: curl ${SERVER}ci/pending.sh | bash
  stage: compile

success:
  allow_failure: true
  script: curl ${SERVER}ci/success.sh | bash
  when: on_success
  stage: status

failure:
  allow_failure: true
  script: curl ${SERVER}ci/failure.sh | bash
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script:
    - cd ${PROJECTNAME}
    - find src -name "*.java" > sources.txt
    - javadoc -private @sources.txt
  stage: javadoc

compile:
  script:
    - chmod -R 777 ./*
    - cd ${PROJECTNAME}
    - ls -l
    - rm -rf ./bin
    - mkdir bin
    - find src -name "*.java" > sources.txt
    - javac -cp . -d ./bin -g -verbose -version -encoding "UTF-8" @sources.txt
  stage: compile
  environment: builds
